// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spring.domain;

import com.spring.domain.Type;

privileged aspect Type_Roo_JavaBean {
    
    public String Type.getName() {
        return this.name;
    }
    
    public void Type.setName(String name) {
        this.name = name;
    }
    
}
